### ISSUE TITLE
会考虑加入多进程吗？

### ISSUE THREAD

**Issue by coolicer** [wl879/Crawl-pet#1]
会考虑加入多进程吗？

这个爬虫是先找好资源放到队列再下载的吗？

**Comment by wl879** [comment]
这个目前来看是不会支持多进程，因为使用的是 leveldb 做为数据库，leveldb 都是单例的，它的优点就是简单。但 nodejs 是支持多并发的吗，也并不是一个一个的下载

**Comment by coolicer** [comment]
@wl879 多进程，我的理解 是它可以平均分配工作给worker。比如1万个下载的，平均分给4个进程，每个进程就可以分担4分一了。
例如：https://github.com/node-modules/cfork

**Comment by wl879** [comment]
@coolicer 嗯，我得学习一下，我对 nodejs 的了解还是比较初级，谢谢你的建议

**Comment by coolicer** [comment]
@wl879 最近在看cluster这块。你也可以看看，对你会有帮忙。
https://cnodejs.org/topic/56e84480833b7c8a0492e20c
